- src/main/java/com/mallangs/global/advice/GlobalExceptionHandler.java
- src/main/java/com/mallangs/global/exception/ErrorCode.java
- src/main/java/com/mallangs/global/exception/ErrorResponse.java
- src/main/java/com/mallangs/global/exception/MallangsCustomException.java
> [feat] 예외처리

- src/main/java/com/mallangs/domain/notification/entity/Notification.java
- src/main/java/com/mallangs/domain/notification/entity/NotificationType.java
> [feat] Notification 엔티티 설계

- src/main/java/com/mallangs/domain/comment/entity/Comment.java
- src/main/java/com/mallangs/domain/comment/entity/PostType.java
> [feat] Comment 댓글 entity 설계

- src/main/java/com/mallangs/domain/community/entity/Category.java
- src/main/java/com/mallangs/domain/community/entity/Like.java
- src/main/java/com/mallangs/domain/community/entity/Likes.java
- src/main/java/com/mallangs/domain/community/repository/CommunityRepository.java
#29 
community category likes 레포지토리 구현
>
> Feature/#29 community category likes 레포지토리 구현

- src/main/java/com/mallangs/domain/community/entity/Likes.java
> [feat] Likes 엔티티 구현

- src/main/java/com/mallangs/domain/article/entity/Article.java
- src/main/java/com/mallangs/domain/article/entity/LostArticle.java
- src/main/java/com/mallangs/domain/article/entity/LostStatus.java
- src/main/java/com/mallangs/domain/article/entity/MapVisibility.java
- src/main/java/com/mallangs/domain/article/entity/RescueArticle.java
> [feat] 글타래 엔티티 설계

- build.gradle
- src/main/java/com/mallangs/domain/community/entity/Category.java
- src/main/java/com/mallangs/domain/community/entity/Community.java
- src/main/java/com/mallangs/domain/community/entity/Like.java
- src/main/java/com/mallangs/domain/community/entity/Likes.java
- src/main/java/com/mallangs/domain/community/repository/CommunityRepository.java
- src/main/java/com/mallangs/global/config/SecurityConfig.java
- src/main/java/com/mallangs/global/config/SwaggerConfig.java
- src/main/resources/application.properties
> Feature/#41 feat 스웨거 구현

- build.gradle
- src/main/java/com/mallangs/domain/jwt/entity/CustomMemberDetails.java
- src/main/java/com/mallangs/domain/jwt/filter/LoginFilter.java
- src/main/java/com/mallangs/domain/member/controller/AddressController.java
- src/main/java/com/mallangs/domain/member/controller/MemberAdminController.java
- src/main/java/com/mallangs/domain/member/controller/MemberController.java
- src/main/java/com/mallangs/domain/member/controller/MemberUserController.java
- src/main/java/com/mallangs/domain/member/dto/MemberAddressRequest.java
- src/main/java/com/mallangs/domain/member/dto/MemberAddressResponse.java
- src/main/java/com/mallangs/domain/member/dto/MemberCreateRequest.java
- src/main/java/com/mallangs/domain/member/dto/MemberSendMailResponse.java
- src/main/java/com/mallangs/domain/member/dto/MemberUpdateRequest.java
- src/main/java/com/mallangs/domain/member/entity/Address.java
- src/main/java/com/mallangs/domain/member/entity/Member.java
- src/main/java/com/mallangs/domain/member/entity/embadded/Nickname.java
- src/main/java/com/mallangs/domain/member/entity/embadded/UserId.java
- src/main/java/com/mallangs/domain/member/repository/MemberRepository.java
- src/main/java/com/mallangs/domain/member/service/AddressService.java
- src/main/java/com/mallangs/domain/member/service/MemberAdminService.java
- src/main/java/com/mallangs/domain/member/service/MemberUserService.java
- src/main/java/com/mallangs/domain/member/util/GeometryUtil.java
- src/main/java/com/mallangs/domain/member/util/PasswordGenerator.java
- src/main/java/com/mallangs/global/config/SecurityConfig.java
- src/test/java/com/mallangs/domain/member/repository/AddressRepositoryTests.java
- src/test/java/com/mallangs/domain/member/repository/MemberRepositoryTests.java
#47# 🔓closed #issue (#뒤에 issue 제거 후 이슈 번호 붙여주세요)
#47 # #️⃣연관된 이슈
> ex) #47 이슈번호, #이슈번호
> member Controller 구현
> 전반적 로그인, 수정 (유효성검사등)
> 잘못된 import 포인트 수정
> 하이버네이트 방언 변경 필요
- spring.jpa.properties.hibernate.dialect=org.hibernate.spatial.dialect.mysql.MySQLSpatialDialect
> 컨트롤러 예외처리 변경 예정
> 프로필 이미지 로직 구현
>
> Feature/#47 포인트 오류 수정 및 컨트롤러 프로토 타입 pr

- src/main/java/com/mallangs/domain/board/controller/BoardController.java
- src/main/java/com/mallangs/domain/board/dto/request/AdminBoardStatusRequest.java
- src/main/java/com/mallangs/domain/board/dto/request/CategoryCreateRequest.java
- src/main/java/com/mallangs/domain/board/dto/request/CategoryUpdateRequest.java
- src/main/java/com/mallangs/domain/board/dto/request/CommunityCreateRequest.java
- src/main/java/com/mallangs/domain/board/dto/request/CommunityUpdateRequest.java
- src/main/java/com/mallangs/domain/board/dto/request/SightingCreateRequest.java
- src/main/java/com/mallangs/domain/board/dto/request/SightingUpdateRequest.java
- src/main/java/com/mallangs/domain/board/dto/response/AdminBoardResponse.java
- src/main/java/com/mallangs/domain/board/dto/response/AdminCategoryResponse.java
- src/main/java/com/mallangs/domain/board/dto/response/CategoryResponse.java
- src/main/java/com/mallangs/domain/board/dto/response/CommunityDetailResponse.java
- src/main/java/com/mallangs/domain/board/dto/response/CommunityListResponse.java
- src/main/java/com/mallangs/domain/board/dto/response/SightingDetailResponse.java
- src/main/java/com/mallangs/domain/board/dto/response/SightingListResponse.java
- src/main/java/com/mallangs/domain/board/entity/Board.java
- src/main/java/com/mallangs/domain/board/entity/BoardType.java
- src/main/java/com/mallangs/domain/board/entity/Category.java
- src/main/java/com/mallangs/domain/board/service/BoardService.java
- src/main/java/com/mallangs/domain/board/service/CategoryService.java
- src/main/java/com/mallangs/global/exception/ErrorCode.java
#66 
Category 관련 서비스와  DTO 구현 하였습니다.
>
> [feat] Category 서비스 & DTO 구현

- src/main/java/com/mallangs/domain/board/controller/BoardController.java
#68 
오타 수정하고 컨트롤러 일단 만들긴 했습니다.
>
> Feature/#68 feat board 컨트롤러 구현

- src/main/java/com/mallangs/domain/board/controller/BoardController.java
- src/main/java/com/mallangs/domain/board/controller/CategoryController.java
- src/main/java/com/mallangs/domain/board/entity/Board.java
- src/main/java/com/mallangs/domain/board/entity/Category.java
- src/main/java/com/mallangs/domain/board/service/BoardService.java
- src/main/java/com/mallangs/domain/board/service/CategoryService.java
- src/main/java/com/mallangs/domain/member/jwt/entity/CustomMemberDetails.java
- src/main/java/com/mallangs/domain/member/jwt/filter/JWTFilter.java
- src/main/java/com/mallangs/domain/member/jwt/filter/LoginFilter.java
#70 
Board 컨트롤러 createCommunity 메서드 관련 클래스들 수정하였습니다
>
> [mod] createCommunity 메서드 관련 수정

- src/main/java/com/mallangs/domain/board/dto/response/CommunityListResponse.java
- src/main/java/com/mallangs/global/config/MvcConfig.java
#74 
카테고리별로 커뮤니티 게시글 조회하는 메서드 수정, MvcConfig에 ngrok 설정 추가하였습니다.
>
> [mod] 카테고리별로 커뮤니티 게시글 조회하는 메서드 수정, MvcConfig에 ngrok 설정 추가

- src/main/java/com/mallangs/domain/board/controller/BoardController.java
- src/main/java/com/mallangs/domain/board/dto/response/CommunityListResponse.java
- src/main/java/com/mallangs/domain/board/entity/BoardType.java
- src/main/java/com/mallangs/domain/board/service/BoardService.java
- src/main/java/com/mallangs/global/config/MvcConfig.java
#80 
Board 게시글 수정하는 메서드 오류 수정하였습니다.
몇몇 클래스 내 주석 내용 삭제 및 자잘한 수정하였습니다.
>
> [mod] Board 게시글 수정 메서드 오류 수정

- src/main/java/com/mallangs/domain/board/controller/BoardController.java
- src/main/java/com/mallangs/domain/board/controller/CategoryController.java
- src/main/java/com/mallangs/domain/board/dto/request/CategoryUpdateRequest.java
- src/main/java/com/mallangs/domain/board/dto/response/AdminBoardsResponse.java
- src/main/java/com/mallangs/domain/board/dto/response/BoardStatusCount.java
- src/main/java/com/mallangs/domain/board/entity/BoardStatus.java
- src/main/java/com/mallangs/domain/board/entity/Category.java
- src/main/java/com/mallangs/domain/board/repository/BoardRepository.java
- src/main/java/com/mallangs/domain/board/repository/CategoryRepository.java
- src/main/java/com/mallangs/domain/board/service/BoardService.java
- src/main/java/com/mallangs/domain/board/service/CategoryService.java
#87 
Board 관리자용 게시글 조회 메서드를 수정합니다.
>
> Feature/#87 [mod] Board 관리자용 게시글 조회 메서드 수정

- src/main/java/com/mallangs/domain/review/dto/PageRequest.java
- src/main/java/com/mallangs/domain/review/dto/ReviewCreateRequest.java
- src/main/java/com/mallangs/domain/review/dto/ReviewInfoResponse.java
- src/main/java/com/mallangs/domain/review/dto/ReviewUpdateRequest.java
- src/main/java/com/mallangs/domain/review/entity/Review.java
- src/main/java/com/mallangs/domain/review/entity/ReviewStatus.java
- src/main/java/com/mallangs/domain/review/repository/ReviewRepository.java
- src/main/java/com/mallangs/domain/review/service/ReviewService.java
- src/main/java/com/mallangs/global/exception/ErrorCode.java
> [feat] Review Service 구현

- src/main/java/com/mallangs/domain/article/service/PlaceArticleCsvService.java
- src/main/java/com/mallangs/domain/pet/controller/PetController.java
- src/main/java/com/mallangs/domain/pet/dto/PetCreateRequest.java
- src/main/java/com/mallangs/domain/pet/service/PetService.java
- src/main/java/com/mallangs/domain/review/controller/ReviewController.java
- src/main/java/com/mallangs/domain/review/dto/ReviewCreateRequest.java
- src/main/java/com/mallangs/domain/review/dto/ReviewUpdateRequest.java
- src/main/java/com/mallangs/domain/review/service/ReviewService.java
> Feature/#92 feat review 컨트롤러 구현

- src/main/java/com/mallangs/domain/article/controller/ArticleController.java
- src/main/java/com/mallangs/domain/article/dto/request/ArticleCreateRequest.java
- src/main/java/com/mallangs/domain/article/dto/request/LostCreateRequest.java
- src/main/java/com/mallangs/domain/article/dto/request/RescueCreateRequest.java
- src/main/java/com/mallangs/domain/article/factory/ArticleFactoryManager.java
- src/main/java/com/mallangs/domain/article/service/ArticleService.java
> [feat] 상속 JSON 변환 추가

- src/main/java/com/mallangs/domain/board/controller/BoardController.java
- src/main/java/com/mallangs/domain/board/controller/CategoryController.java
- src/main/java/com/mallangs/domain/board/dto/request/CategoryCreateRequest.java
- src/main/java/com/mallangs/domain/board/dto/request/CategoryUpdateRequest.java
- src/main/java/com/mallangs/domain/board/dto/request/CommunityCreateRequest.java
- src/main/java/com/mallangs/domain/board/dto/request/CommunityUpdateRequest.java
- src/main/java/com/mallangs/domain/board/dto/request/SightingCreateRequest.java
- src/main/java/com/mallangs/domain/board/dto/request/SightingUpdateRequest.java
- src/main/java/com/mallangs/domain/board/dto/response/AdminCategoryResponse.java
- src/main/java/com/mallangs/domain/board/dto/response/CategoryResponse.java
- src/main/java/com/mallangs/domain/board/dto/response/CommunityDetailResponse.java
- src/main/java/com/mallangs/domain/board/dto/response/SightingDetailResponse.java
- src/main/java/com/mallangs/domain/board/dto/response/SightingListResponse.java
- src/main/java/com/mallangs/domain/board/entity/Board.java
- src/main/java/com/mallangs/domain/board/entity/Category.java
- src/main/java/com/mallangs/domain/board/entity/CategoryLevel.java
- src/main/java/com/mallangs/domain/board/repository/BoardRepository.java
- src/main/java/com/mallangs/domain/board/service/BoardService.java
- src/main/java/com/mallangs/domain/board/service/CategoryService.java
- src/main/java/com/mallangs/global/exception/ErrorCode.java
- src/test/java/com/mallangs/domain/board/repository/BoardRepositoryTest.java
#99 
Board, Category 서비스, 컨트롤러 수정, 이미지 테이블 생성에 따른 관련 수정하였습니다.
>
> [mod] Board, Category 서비스, 컨트롤러 수정, 이미지 테이블 생성에 따른 관련 수정

- src/main/java/com/mallangs/domain/chat/controller/ChatMessageController.java
- src/main/java/com/mallangs/domain/chat/dto/response/ChatMessageToDTOResponse.java
- src/main/java/com/mallangs/domain/chat/service/ChatMessageService.java
- src/main/java/com/mallangs/domain/chat/service/ChatRoomService.java
- src/main/java/com/mallangs/domain/member/controller/AddressController.java
- src/main/java/com/mallangs/domain/member/controller/AuthController.java
- src/main/java/com/mallangs/domain/member/controller/MemberAdminController.java
- src/main/java/com/mallangs/domain/member/controller/MemberFileController.java
- src/main/java/com/mallangs/domain/member/controller/MemberUserController.java
- src/main/java/com/mallangs/domain/member/service/AddressService.java
- src/main/java/com/mallangs/global/config/MvcConfig.java
- src/main/java/com/mallangs/global/config/SecurityConfig.java
- src/main/java/com/mallangs/global/exception/ErrorCode.java
- src/test/java/com/mallangs/domain/chat/repository/ChatRoomRepositoryTest.java
> Add/프론트 연동 url추가

- src/main/java/com/mallangs/domain/board/controller/BoardController.java
- src/main/java/com/mallangs/domain/board/repository/BoardRepository.java
- src/main/java/com/mallangs/domain/board/service/BoardService.java
#104 
각 게시판 내 전체 검색 기능 추가하고 pageNation 시작 번호 수정하였습니다.
>
> [add] Board 게시판 종류별 전체 게시글 검색 기능 추가

- src/main/java/com/mallangs/domain/article/controller/ArticleController.java
- src/main/java/com/mallangs/domain/article/dto/response/MapBoundsResponse.java
- src/main/java/com/mallangs/domain/article/repository/JdbcLocationRepository.java
- src/main/java/com/mallangs/domain/article/repository/LocationRepository.java
- src/main/java/com/mallangs/domain/article/service/LocationService.java
#110 
- jpql 을 이용할 경우 파라미터 인식을 못하는 문제 발생 
- JDBC 템플릿 이용
>
> [feat] 지도에서 글타래 조회 API 수정

- src/main/java/com/mallangs/domain/board/controller/BoardController.java
> [mod] Board 검색 엔드포인트 수정

- src/main/java/com/mallangs/global/filter/RedirectHttpsToHttpFilter.java
> Feature/#95 리다이렉트 https->http

- src/main/java/com/mallangs/domain/chat/controller/ChatMessageController.java
- src/main/java/com/mallangs/domain/chat/controller/ChatRoomController.java
- src/main/java/com/mallangs/domain/chat/controller/WebSocketDocumentationController.java
- src/main/java/com/mallangs/domain/member/controller/MemberAdminController.java
- src/main/java/com/mallangs/domain/member/controller/MemberFileController.java
- src/main/java/com/mallangs/domain/member/controller/MemberUserController.java
- src/main/java/com/mallangs/domain/member/entity/Member.java
- src/main/java/com/mallangs/global/config/SecurityConfig.java
- src/main/java/com/mallangs/global/handler/StompFileHandler.java
- src/main/resources/application-dev.properites
> Add/admin change api 관리자로 역할 변경 API 추가

- src/main/java/com/mallangs/global/jwt/filter/JWTFilter.java
> fix: 코드 수정

- src/main/java/com/mallangs/domain/article/controller/TourApiController.java
- src/main/java/com/mallangs/domain/board/controller/BoardController.java
- src/main/java/com/mallangs/domain/board/controller/CategoryController.java
- src/main/java/com/mallangs/domain/comment/controller/CommentController.java
- src/main/java/com/mallangs/domain/member/controller/AuthController.java
- src/main/java/com/mallangs/domain/pet/controller/PetController.java
- src/main/java/com/mallangs/domain/review/controller/ReviewController.java
> [mod] api 엔드포인트 버전 명시

- src/main/java/com/mallangs/domain/chat/controller/test/ChatViewControllerTest.java
- src/main/java/com/mallangs/domain/image/entity/Image.java
- src/main/java/com/mallangs/domain/image/entity/ImageOrder.java
- src/main/java/com/mallangs/domain/image/repository/ImageRepository.java
- src/main/java/com/mallangs/global/config/SecurityConfig.java
- src/main/java/com/mallangs/global/exception/ErrorCode.java
- src/main/java/com/mallangs/global/jwt/filter/JWTFilter.java
- src/main/java/com/mallangs/web/HomeController.java
> Feature/#137 add home contoller 추가

- .github/workflows/CICD.yml
- build.gradle
- src/main/java/com/mallangs/domain/image/dto/ImageResponse.java
- src/main/java/com/mallangs/global/s3/S3Config.java
- src/main/java/com/mallangs/global/s3/S3Controller.java
- src/main/java/com/mallangs/global/s3/S3Service.java
s3 Config
s3 Service
s3 Controller
>
> [feat] s3 환경 설정

- src/main/java/com/mallangs/domain/article/controller/ArticleController.java
- src/main/java/com/mallangs/domain/article/repository/ArticleRepository.java
- src/main/java/com/mallangs/domain/article/repository/JdbcLocationRepository.java
- src/main/java/com/mallangs/domain/article/repository/LocationRepository.java
- src/main/java/com/mallangs/domain/article/service/ArticleService.java
- src/main/java/com/mallangs/domain/article/service/LocationService.java
- src/main/java/com/mallangs/global/config/SecurityConfig.java
- src/main/java/com/mallangs/global/exception/ErrorCode.java
- src/main/java/com/mallangs/global/jwt/filter/JWTFilter.java
#142 
- 권한별 로직 수정
- 글타래 대분류 추가
- 실종 글타래 별도 조회 로직 추가
- 공공데이터 장소, 사용자 등록 장소 구분 및 메서드 수정
- /api/articles/public/ 로 시작하는 경로 필터 제외
>
> [feat] 글타래 로직 수정

- src/main/java/com/mallangs/domain/pet/service/PetService.java
- src/main/java/com/mallangs/domain/review/service/ReviewService.java
비회원 일 경우에도 (CustomMemberDetails 가 null) 
가능한 API 설정
```java
// 리뷰 조회 (리뷰 ID로)
@GetMapping("/api/v1/place-articles/{placeArticleId}/reviews/{reviewId}")
// 장소에 달린 리뷰 목록 조회
@GetMapping("/api/v1/place-articles /{placeArticleId}/reviews")
// 특정 장소의 평균 평점 계산
@GetMapping("/api/v1/place-articles /{placeArticleId}/reviews/average-score")
//반려동물 조회
@GetMapping("/api/v1/pets/{petId}")
//근처 반려동물 조회
@GetMapping("/api/v1/pets/nearby")
```
>
> [feat]비회원 접근 설정

- src/main/java/com/mallangs/domain/image/controller/ImageController.java
- src/main/java/com/mallangs/domain/image/entity/Image.java
- src/main/java/com/mallangs/domain/image/repository/ImageRepository.java
- src/main/java/com/mallangs/domain/image/service/ImageService.java
- src/main/java/com/mallangs/global/exception/ErrorCode.java
> [mod] Image 채팅 관련 추가

- src/main/java/com/mallangs/domain/article/controller/ArticleController.java
- src/main/java/com/mallangs/domain/article/dto/request/ArticleCreateRequest.java
- src/main/java/com/mallangs/domain/article/dto/request/LostCreateRequest.java
- src/main/java/com/mallangs/domain/article/dto/request/PlaceCreateRequest.java
- src/main/java/com/mallangs/domain/article/dto/request/RescueCreateRequest.java
- src/main/java/com/mallangs/domain/article/validation/ValidationGroups.java
> [feat] 글타래 validation group 설정

- src/main/java/com/mallangs/domain/article/dto/request/PlaceCreateRequest.java
> feat: BuilderDefault 설정

- .github/workflows/CICDdevelop.yml
- src/main/java/com/mallangs/domain/pet/entity/Pet.java
> [feat]  main develop 브랜치 cicd 워크플로우 분리

- src/main/java/com/mallangs/domain/image/dto/ImageDto.java
- src/main/java/com/mallangs/domain/image/service/ImageService.java
#168 
요구 사항에 따라 응답 구조 수정하였습니다.
>
> Feature/#168 mod image 응답 구조 변경

- src/main/java/com/mallangs/domain/article/controller/ArticleController.java
- src/main/java/com/mallangs/domain/article/dto/request/ArticleCreateRequest.java
- src/main/java/com/mallangs/domain/article/dto/request/LostCreateRequest.java
- src/main/java/com/mallangs/domain/article/dto/response/ArticlePageResponse.java
- src/main/java/com/mallangs/domain/article/repository/ArticleRepository.java
- src/main/java/com/mallangs/domain/article/repository/JdbcLocationRepository.java
- src/main/java/com/mallangs/domain/article/service/ArticleService.java
- src/main/java/com/mallangs/domain/article/service/LocationService.java
- src/main/java/com/mallangs/global/config/SecurityConfig.java
- src/main/java/com/mallangs/global/jwt/filter/JWTFilter.java
#173 
- db 조회 시 오류 해결
- jpql, jdbc 쿼리 차이에 따른 수정
- 비회원 접근 가능 경로 수정
- 권한별 로직 수정
- 장소 / 사용자 등록 장소 차이에 따른 로직 수정
>
> [feat] db 조회 메서드 수정 및 권한 관련 로직 수정

- src/main/java/com/mallangs/domain/board/controller/BoardController.java
- src/main/java/com/mallangs/domain/board/dto/request/AdminBoardStatusRequest.java
- src/main/java/com/mallangs/domain/board/dto/request/CategoryCreateRequest.java
- src/main/java/com/mallangs/domain/board/dto/request/CategoryUpdateRequest.java
- src/main/java/com/mallangs/domain/board/dto/request/CommunityCreateRequest.java
- src/main/java/com/mallangs/domain/board/dto/request/CommunityUpdateRequest.java
- src/main/java/com/mallangs/domain/board/dto/request/SightingCreateRequest.java
- src/main/java/com/mallangs/domain/board/dto/request/SightingUpdateRequest.java
- src/main/java/com/mallangs/domain/board/dto/response/AdminBoardResponse.java
- src/main/java/com/mallangs/domain/board/dto/response/AdminBoardsResponse.java
- src/main/java/com/mallangs/domain/board/dto/response/AdminCategoryResponse.java
- src/main/java/com/mallangs/domain/board/dto/response/BoardStatusCount.java
- src/main/java/com/mallangs/domain/board/dto/response/CategoryResponse.java
- src/main/java/com/mallangs/domain/board/dto/response/CommunityDetailResponse.java
- src/main/java/com/mallangs/domain/board/dto/response/CommunityListResponse.java
- src/main/java/com/mallangs/domain/board/dto/response/PageResponse.java
- src/main/java/com/mallangs/domain/board/dto/response/SightingDetailResponse.java
- src/main/java/com/mallangs/domain/board/dto/response/SightingListResponse.java
- src/main/java/com/mallangs/domain/board/entity/Board.java
- src/main/java/com/mallangs/domain/board/entity/Category.java
- src/main/java/com/mallangs/domain/board/entity/CategoryLevel.java
- src/main/java/com/mallangs/domain/board/repository/BoardRepository.java
- src/main/java/com/mallangs/domain/board/service/BoardService.java
- src/test/java/com/mallangs/domain/board/repository/CategoryRepositoryTest.java
> [mod] API 수정

- src/main/java/com/mallangs/domain/board/controller/CategoryController.java
- src/main/java/com/mallangs/domain/board/repository/CategoryRepository.java
- src/main/java/com/mallangs/domain/board/service/CategoryService.java
- src/main/java/com/mallangs/global/config/SecurityConfig.java
#183 
Category 전부 관리자 권한으로 변경 및 기타 수정
SecurityConfig 경로 인가에 category도 추가하였습니다.
>
> [mod] Board 카테고리 api 수정, SecurityConfig 경로 인가에 category 추가

- src/main/java/com/mallangs/domain/board/controller/BoardController.java
- src/main/java/com/mallangs/domain/board/repository/BoardRepository.java
- src/main/java/com/mallangs/domain/board/service/BoardService.java
- src/main/java/com/mallangs/domain/board/service/CategoryService.java
- src/main/java/com/mallangs/global/exception/ErrorCode.java
#189 
관리자 권한 메세지 설정, 로그인 메세지 설정, 게시글 번호 조회 예외 메세지 설정
>
> [mod] 관리자 권한 메세지 설정, 로그인 메세지 설정, 게시글 번호 조회 예외 메세지 설정

- src/main/java/com/mallangs/domain/pet/controller/PetController.java
- src/main/java/com/mallangs/domain/pet/dto/PetNearbyPageResponse.java
- src/main/java/com/mallangs/domain/pet/dto/PetPageResponse.java
- src/main/java/com/mallangs/domain/pet/service/PetService.java
- src/main/java/com/mallangs/domain/review/controller/ReviewController.java
- src/main/java/com/mallangs/domain/review/dto/ReviewPageResponse.java
- src/main/java/com/mallangs/domain/review/service/ReviewService.java
비회원용 public 엔드포인트 추가
memberId로 대표 말랑이 검색 추가
>
> [feat] 비회원 엔드포인트

- src/main/java/com/mallangs/domain/article/controller/ArticleController.java
- src/main/java/com/mallangs/domain/article/service/ArticleService.java
> [feat] 비회원 단건 조회 메서드 수정

- src/main/java/com/mallangs/global/config/SecurityConfig.java
- src/main/java/com/mallangs/global/jwt/filter/JWTFilter.java
- src/main/resources/templates/websocket_test.html
> FIX/ 채팅 시큐리티 필터 추가

- src/main/java/com/mallangs/domain/member/controller/MemberUserController.java
- src/main/java/com/mallangs/domain/member/dto/MemberAddressRequest.java
- src/main/java/com/mallangs/domain/member/dto/MemberGetResponse.java
- src/main/java/com/mallangs/domain/member/dto/MemberUpdateRequest.java
- src/main/java/com/mallangs/domain/member/dto/response/MemberGetByOtherResponse.java
- src/main/java/com/mallangs/domain/member/entity/Member.java
- src/main/java/com/mallangs/domain/member/repository/MemberRepository.java
- src/main/java/com/mallangs/domain/member/service/AddressService.java
- src/main/java/com/mallangs/domain/member/service/MemberUserService.java
- src/main/java/com/mallangs/global/config/SecurityConfig.java
- src/main/java/com/mallangs/global/jwt/filter/JWTFilter.java
#199 # 🔓closed #issue (#뒤에 issue 제거 후 이슈 번호 붙여주세요)
#199 # #️⃣연관된 이슈
> 비회원 단건 조회
로그인 되어있지 않아도 조회가능하게 수정
회원 정보에서 주소를 제외한 나머지 정보 조회가능
> [add] 회원 (타인이 조회할때 ) 추가

- src/main/java/com/mallangs/domain/member/controller/MemberUserController.java
- src/main/java/com/mallangs/global/exception/ErrorCode.java
- src/main/java/com/mallangs/global/jwt/filter/JWTFilter.java
> 리프레시 토큰 제거

- src/main/java/com/mallangs/domain/pet/controller/PetController.java
- src/main/java/com/mallangs/domain/pet/repository/PetRepository.java
- src/main/java/com/mallangs/domain/pet/service/PetService.java
- src/main/java/com/mallangs/domain/review/service/ReviewService.java
- src/main/java/com/mallangs/global/exception/ErrorCode.java
- src/test/java/com/mallangs/domain/board/repository/BoardRepositoryTest.java
- src/test/java/com/mallangs/domain/board/repository/CategoryRepositoryTest.java
> Feature/#201 fix 위치 데이터베이스 오류 설정

- src/main/java/com/mallangs/domain/article/controller/ArticleController.java
- src/main/java/com/mallangs/domain/article/repository/JdbcLocationRepository.java
> [feat] 지도 전체 조회 수정, 공개 조건 추가

- src/main/java/com/mallangs/domain/board/controller/BoardController.java
- src/main/java/com/mallangs/domain/board/dto/response/CommunityListResponse.java
- src/main/java/com/mallangs/domain/board/dto/response/SightingListResponse.java
- src/main/java/com/mallangs/global/jwt/filter/JWTFilter.java
> [mod] Board api 수정2

- src/main/java/com/mallangs/domain/member/dto/MemberAddressRequest.java
- src/main/java/com/mallangs/domain/member/dto/MemberCreateRequest.java
- src/main/java/com/mallangs/global/config/WebSocketConfig.java
- src/main/resources/templates/websocket_test.html
#211 # 🔓closed #211 issue (#뒤에 issue 제거 후 이슈 번호 붙여주세요)
#211 # #️⃣연관된 이슈
>: 웹소켓 heart beat 주기 추가.
이슈에 대한 구체적인 설명을 작성하세요. 
- 웹소켓- stomp - sockjs의 경우 heart beat 를 구현하지 않아도 자동 설정되는데, 눈으로 확인하고자, messageBroker에 heart beat 주기를 수동으로 설정하였다.
- 서버 heart beat 주기 코드 추가
- 클라이언트 주기 추가
- 테스트
> Feature/#heart beat 추가

- src/main/java/com/mallangs/domain/comment/service/CommentService.java
> [mod] 댓글 조회 수정

- src/main/resources/application-dev.properties
> [mod] TimeZone Asia/Seoul 설정

- src/main/java/com/mallangs/domain/comment/service/CommentService.java
- src/main/resources/application-dev.properties
> [add] TimeZone 설정

- src/main/resources/application-dev.properties
> Feature/#222 add timezone 설정 2

- script/articleTest.js
- script/boardTest.js
- script/docker-compose.yml
디벨롭에서 오류가 있는데, 메인에서는 있지 않은 상태이다.
어떤 차이가 있는지 알아보기 위해 develop을 main으로 pr해서 테스트 해본다.
> Feature/Test develop -> main 

- .github/workflows/CICDdevelop.yml
> [fix] develop CI/CD 수정

- .github/workflows/CICDdevelop.yml
> 깃 액션 v4로 upload 업데이트

- .github/workflows/CICD.yml
> [feat] main branch CI/CD 수정

- src/main/java/com/mallangs/domain/chat/dto/response/ChatRoomResponse.java
- src/main/java/com/mallangs/domain/chat/service/ChatMessageService.java
채팅방 코드 수정 - 참여 채팅방 조회시 chatRoomId 반환
> 채팅방 코드 수정 - 참여 채팅방 조회시 chatRoomId 반환

- src/main/java/com/mallangs/global/config/SecurityConfig.java
> ai 시큐리티 추가

- .github/workflows/CICD.yml
- .github/workflows/CICDdevelop.yml
> CI/CD 수정 -> Credential 삭제

- src/main/java/com/mallangs/global/jwt/filter/JWTFilter.java
> [fix] ai 컨트롤러 jwt 제외

- build.gradle
- src/main/java/com/mallangs/domain/ai/AIPromptController.java
> [fix] AI 메서드 로직 변경

- src/main/java/com/mallangs/global/config/MvcConfig.java
- src/main/java/com/mallangs/global/config/SecurityConfig.java
> https 시큐리티 추가

- build.gradle
- src/main/java/com/mallangs/global/config/SecurityConfig.java
> [feat] 헬스체크 추가

- build.gradle
- src/main/java/com/mallangs/global/config/MvcConfig.java
- src/main/java/com/mallangs/global/config/SecurityConfig.java
https://mallang-place.vercel.app/ [시큐리티에 추가](https://github.com/prgrms-web-devcourse-final-project/WEB1_2_Mallangs_BE/commit/1747ad7733a6fd0856d087bb421b2cebd56b31f3)
> https://mallang-place.vercel.app/ 시큐리티에 추가

- src/main/java/com/mallangs/domain/member/dto/MemberCreateRequest.java
> [fix] 회원정보 수정 90 -> 180

- build.gradle
- src/main/java/com/mallangs/domain/ai/AIPromptController.java
- src/main/java/com/mallangs/domain/article/service/ArticleService.java
- src/main/java/com/mallangs/domain/chat/redis/RedisPublisher.java
- src/main/java/com/mallangs/domain/chat/redis/RedisSubscriber.java
- src/main/java/com/mallangs/domain/chat/service/ChatMessageService.java
- src/main/java/com/mallangs/global/config/RedisConfig.java
AI 서비스 로직 수정, 채팅 Redis publisher 추가
> AI 서비스 로직 수정, 채팅 Redis publisher 추가

- src/main/java/com/mallangs/domain/article/service/LocationService.java
- src/main/java/com/mallangs/global/exception/ErrorCode.java
- src/main/java/com/mallangs/global/jwt/filter/JWTFilter.java
#270 # 🔓closed #270 issue (#뒤에 issue 제거 후 이슈 번호 붙여주세요)
#270 # #️⃣연관된 이슈
> jwtfilter 예외처리 중복현상 해결
>
> [fix] jwtfilter 예외처리 중복현상 해결

- src/main/java/com/mallangs/domain/ai/AIPromptController.java
- src/main/java/com/mallangs/global/exception/ErrorCode.java
#268 # #️⃣연관된 이슈
> [fix] ai lostArticle 검증 로직 추가
articleResponse가 lostArticle이 아니라면, 예외발생 ( lostArticle이 아닙니다. articleId를 확인해주세요 ) 
>
> [fix] ai lostArticle 검증 로직 추가

- src/main/java/com/mallangs/global/config/SecurityConfig.java
> #268 
> /actuator/** spring security 차단 해제
>
> [add] /actuator/** spring security 차단 해제

- build.gradle
- src/main/java/com/mallangs/domain/ai/AIPromptController.java
- src/main/java/com/mallangs/domain/ai/OpenAiPromptController.java
#268# 🔓closed #issue (#뒤에 issue 제거 후 이슈 번호 붙여주세요)
#268 # #️⃣연관된 이슈
> chatgpt ai 코드 추가,
너의이름은? 이라는 간단한 질문
>
> Feature/#268 ai prompt 추가

- src/main/java/com/mallangs/domain/ai/OpenAiPromptController.java
>json으로 받아야했던 message를 String으로 로직내에서 받을 수 있게 고정함.
>
> requestBody 수정

- src/main/java/com/mallangs/domain/ai/OpenAiPromptController.java
- src/main/java/com/mallangs/global/jwt/filter/JWTFilter.java
#268 # 🔓closed #268 issue (#뒤에 issue 제거 후 이슈 번호 붙여주세요)
#268 # #️⃣연관된 이슈
> 토큰 만료시 발생하는 에러처리 수정 -> utf-8 변환 코드 입력
> 기존 ai 코드 질문이던 "너의 이름은?" 을 수정 
-> 실종글타래 id입력 시 목격게시글 확인하고 비슷한 게시글 불러오는 코드 추가
>
> [fix] 토큰 만료시 에러처리 utf-8 변환 추가, ai 코드 질문 수정

- src/main/java/com/mallangs/domain/ai/OpenAiPromptController.java
ai 질문 코드 수정
=> 예시 응답을 실제응답에 반영하는 오류가 있었음. 예시 응답을 약하게 반응하도록, "이건 예시야! 라고 주의줌"
> ai 질문 코드 수정

- src/main/java/com/mallangs/domain/ai/OpenAiPromptController.java
[fix] ai 질문 수정
> ai 질문의 정확도가 낮아, 더욱 구체적이고 명확한 질문을 하도록 수정하였습니다.
> [fix] ai 질문 수정
